apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: "app"
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
spec:
  description: "app applications"
  sourceRepos:
    - "*"
  destinations:
    - server: https://kubernetes.default.svc
      namespace: files
    - server: https://kubernetes.default.svc
      namespace: habitsync
    - server: https://kubernetes.default.svc
      namespace: sso-debug
    - server: https://kubernetes.default.svc
      namespace: vaultwarden
    - server: https://kubernetes.default.svc
      namespace: vikunja
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
