apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mail-relay
  annotations:
    argocd.argoproj.io/sync-wave: "-10"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: mail-relay
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        smtp_passwd: |
          relay@d-reis.com: bcrypt:{{ .SMTP_RELAY_PASSWORD_HASH }}
        sender_map: |
          relay@d-reis.com: d-reis.com
        UPSTREAM_SMTP_USERNAME: "{{ .UPSTREAM_SMTP_USERNAME }}"
        UPSTREAM_SMTP_PASSWORD: "{{ .UPSTREAM_SMTP_PASSWORD }}"
  data:
    - secretKey: SMTP_RELAY_PASSWORD_HASH
      remoteRef:
        key: /external-secrets/mail-relay/sender-password-hash
    - secretKey: UPSTREAM_SMTP_USERNAME
      remoteRef:
        key: /external-secrets/mail-relay/upstream-username
    - secretKey: UPSTREAM_SMTP_PASSWORD
      remoteRef:
        key: /external-secrets/mail-relay/upstream-password
