apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: "base"
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - git:
        repoURL: https://github.com/pikaro/k8s.git
        revision: main
        files:
          - path: "argocd/catalog/base/*.yaml"

  template:
    metadata:
      name: "{{ .name }}"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ dig "namespace" .name . }}'

  templatePatch: |
    {{- $name := .name }}
    {{- $sourceType := dig "sourceType" "helm" . }}
    {{- $basePath := dig "basePath" (printf "services/base/%s" $name) . }}
    {{- $chart := dig "chart" $name . }}
    {{- $releaseName := dig "releaseName" $name . }}
    {{- $valuesFile := dig "valuesFile" (printf "services/base/%s/values.yaml" $name) . }}
    {{- $requirementsPath := dig "requirementsPath" "" . }}
    {{- $resourcesPath := dig "resourcesPath" "" . }}
    {{- $serverSideApply := eq (dig "serverSideApply" "false" .) "true" }}
    spec:
      {{- if $serverSideApply }}
      syncPolicy:
        syncOptions:
          - ServerSideApply=true
      {{- end }}
      sources:
        {{- if eq $sourceType "kustomize" }}
        - repoURL: https://github.com/pikaro/k8s.git
          targetRevision: main
          path: {{ $basePath }}
        {{- else if eq $sourceType "helm" }}
        {{- if $requirementsPath }}
        - repoURL: https://github.com/pikaro/k8s.git
          targetRevision: main
          path: {{ $requirementsPath }}
        {{- end }}
        - repoURL: {{ .chartRepo }}
          chart: {{ $chart }}
          targetRevision: {{ .chartVersion }}
          helm:
            releaseName: {{ $releaseName }}
            valueFiles:
              - $values/{{ $valuesFile }}
        - repoURL: https://github.com/pikaro/k8s.git
          targetRevision: main
          ref: values
        {{- if $resourcesPath }}
        - repoURL: https://github.com/pikaro/k8s.git
          targetRevision: main
          path: {{ $resourcesPath }}
        {{- end }}
        {{- end }}
