apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: platform
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/pikaro/k8s.git
        revision: main
        files:
          - path: argocd/catalog/platform/*.yaml

  template:
    metadata:
      name: "{{ .name }}"
    spec:
      project: default
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"

  templatePatch: |
    spec:
      sources:
        {{- if .requirementsPath }}
        - repoURL: https://github.com/pikaro/k8s.git
          targetRevision: main
          path: {{ .requirementsPath }}
        {{- end }}
        - repoURL: {{ .chartRepo }}
          chart: {{ .chart }}
          targetRevision: {{ .chartVersion }}
          helm:
            releaseName: {{ .name }}
            valueFiles:
              - $values/{{ .valuesFile }}
        - repoURL: https://github.com/pikaro/k8s.git
          targetRevision: main
          ref: values
        {{- if .resourcesPath }}
        - repoURL: https://github.com/pikaro/k8s.git
          targetRevision: main
          path: {{ .resourcesPath }}
        {{- end }}
