apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: assistant

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
    app.kubernetes.io/name: voice-assistant-dashboard
    app.kubernetes.io/part-of: assistant

configMapGenerator:
  - name: voice-assistant-dashboard
    files:
      - voice-assistant.json
