apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: openproject-admin-password
  namespace: openproject
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  length: 32
  symbols: 0
  noUpper: false
  allowRepeat: true
  secretKeys:
    - password
