apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: openproject-admin-password
  namespace: openproject
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  length: 32
  symbols: 0
  noUpper: false
  allowRepeat: true
  secretKeys:
    - password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openproject-admin-password
  namespace: openproject
  annotations:
    argocd.argoproj.io/sync-wave: "-19"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshPolicy: CreatedOnce
  target:
    name: openproject-admin-password
    creationPolicy: Orphan
    template:
      engineVersion: v2
      type: Opaque
      data:
        password: "{{ .password }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: openproject-admin-password
