apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openproject-smtp
  namespace: openproject
  annotations:
    argocd.argoproj.io/sync-wave: "-17"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: openproject-smtp
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        OPENPROJECT_EMAIL__DELIVERY__METHOD: smtp
        OPENPROJECT_SMTP__ADDRESS: mail-relay.mail.svc.cluster.local
        OPENPROJECT_SMTP__PORT: "587"
        OPENPROJECT_SMTP__DOMAIN: d-reis.com
        OPENPROJECT_SMTP__AUTHENTICATION: plain
        OPENPROJECT_SMTP__USER__NAME: relay@d-reis.com
        OPENPROJECT_SMTP__PASSWORD: "{{ .SMTP_RELAY_PASSWORD }}"
        OPENPROJECT_SMTP__ENABLE__STARTTLS__AUTO: "false"
        OPENPROJECT_MAIL__FROM: openproject@d-reis.com
  data:
    - secretKey: SMTP_RELAY_PASSWORD
      remoteRef:
        key: /external-secrets/mail-relay/sender-password
