apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: traefik
  namespace: traefik
  labels:
    app.kubernetes.io/name: traefik
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/component: metrics
spec:
  jobLabel: traefik
  namespaceSelector:
    matchNames:
      - traefik
  selector:
    matchLabels:
      app.kubernetes.io/name: traefik
      app.kubernetes.io/instance: traefik-traefik
      app.kubernetes.io/component: metrics
  endpoints:
    - port: metrics
      path: /metrics
      scheme: https
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        caFile: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        serverName: kubernetes.default.svc
      relabelings:
        - targetLabel: __address__
          replacement: kubernetes.default.svc:443
        - targetLabel: instance
          replacement: traefik-metrics.traefik.svc.cluster.local:9101
        - targetLabel: __metrics_path__
          replacement: /api/v1/namespaces/traefik/services/http:traefik-metrics:9101/proxy/metrics
