name: argocd
chartRepo: https://argoproj.github.io/argo-helm
chart: argo-cd
chartVersion: 9.7.0
authentik:
  name: ArgoCD
  group: Management
  url: https://argo.d-reis.com
  directoryGroups:
    - argocd-users
    - argocd-admins
  oidc:
    redirectUris:
      - https://argo.d-reis.com/auth/callback
      - https://localhost:8085/auth/callback
    secretLabels:
      app.kubernetes.io/part-of: argocd
      app.kubernetes.io/name: argocd-sso
