name: mail-test
namespace: mail
sourceType: kustomize
skipDryRunOnMissingResource: "true"
authentik:
  name: Mail Test
  slug: mail-test
  protocol: proxy
  group: Management
  url: https://mail-test.k8s.d-reis.com
  proxy:
    mode: forward_single
    externalHost: https://mail-test.k8s.d-reis.com
