name: openebs
namespace: openebs
chartRepo: https://openebs.github.io/openebs
chart: openebs
chartVersion: 4.4.0
valuesFile: services/platform/openebs/values.yml
requirementsPath: ""
resourcesPath: services/platform/openebs/resources
