namespace: assistant

labels:
  d-reis.com/context: ai
annotations:
  d-reis.com/context: ai

image:
  repository: ghcr.io/pikaro/ai-assistant
  tag: sha-1b069bc

additionalResources:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: assistant-config
    data:
      config.yaml: |
        model_id: qwen3-4b

additionalVolumes:
  - name: config
    configMap:
      name: assistant-config
      items:
        - key: config.yaml
          path: config.yaml

container:
  env:
    ASSISTANT_CONFIG_FILE: /config.yaml
    LOG_LEVEL: DEBUG
  volumeMounts:
    - name: config
      mountPath: /config.yaml
      subPath: config.yaml
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true
  startupProbe:
    enabled: true

service:
  port: 80

ingress:
  enabled: true
  host: hal.d-reis.com
  tls:
    secretName: assistant-tls
  annotations:
    external-dns.alpha.kubernetes.io/hostname: hal.d-reis.com
    external-dns.alpha.kubernetes.io/target: thule.d-reis.com
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
  authentikOutpost:
    enabled: true

networkPolicy:
  ingressNamespaces:
    - traefik
