ollama:
  enabled: false

pipelines:
  enabled: true

tika:
  enabled: false

terminals:
  enabled: false

websocket:
  enabled: true
  manager: redis
  redis:
    enabled: true

replicaCount: 1

ingress:
  enabled: true
  class: "traefik"
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ai.d-reis.com,ai.k8s.d-reis.com
    external-dns.alpha.kubernetes.io/target: thule.d-reis.com
    cert-manager.io/cluster-issuer: letsencrypt
  host: "ai.d-reis.com"
  additionalHosts:
    - "ai.k8s.d-reis.com"
  tls: true
  existingSecret: "openwebui-tls"

persistence:
  enabled: true
  size: 2Gi
  storageClass: "zfs"
  # TODO: Move to S3

service:
  type: ClusterIP

enableOpenaiApi: false
# openaiBaseApiUrls:
#   - http://llm.svc.cluster.local:8000/v1
# openaiApiKeysExistingSecret: openwebui-openai-connections
# openaiApiKeysExistingSecretKey: api-keys

extraEnvVars:
  - name: ENABLE_PERSISTENT_CONFIG
    value: "false"
  - name: DATABASE_TYPE
    value: "postgresql"
  - name: DATABASE_USER
    valueFrom:
      secretKeyRef:
        name: openwebui-database
        key: username
  - name: DATABASE_PASSWORD
    valueFrom:
      secretKeyRef:
        name: openwebui-database
        key: password
  - name: DATABASE_HOST
    value: cnpg-cluster-rw.cnpg-database.svc.cluster.local
  - name: DATABASE_PORT
    value: "5432"
  - name: DATABASE_NAME
    value: "openwebui"
  - name: ENABLE_LOGIN_FORM
    value: "false"
  - name: OAUTH_AUTO_REDIRECT
    value: "true"
  # - name: AUDIO_STT_ENGINE
  #   value: openai
  # - name: AUDIO_STT_MODEL
  #   value: whisper-1
  # - name: AUDIO_STT_OPENAI_API_BASE_URL
  #   value: http://whisper.stt.svc.cluster.local:8000/v1
  # - name: AUDIO_STT_OPENAI_API_KEY
  #   valueFrom:
  #     secretKeyRef:
  #       name: openwebui-audio
  #       key: stt-api-key
  # - name: AUDIO_TTS_ENGINE
  #   value: openai
  # - name: AUDIO_TTS_MODEL
  #   value: tts-1
  # - name: AUDIO_TTS_VOICE
  #   value: alloy
  # - name: AUDIO_TTS_OPENAI_API_BASE_URL
  #   value: http://kokoro.tts.svc.cluster.local:8880/v1
  # - name: AUDIO_TTS_OPENAI_API_KEY
  #   valueFrom:
  #     secretKeyRef:
  #       name: openwebui-audio
  #       key: tts-api-key

podSecurityContext:
  fsGroupChangePolicy: Always
  sysctls: []
  supplementalGroups: []
  fsGroup: 1001

containerSecurityContext:
  runAsUser: 1001
  runAsGroup: 1001
  runAsNonRoot: true
  privileged: false
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: "RuntimeDefault"

sso:
  enabled: true
  enableSignup: true
  mergeAccountsByEmail: true
  # enableRoleManagement: true
  enableGroupManagement: true
  oidc:
    enabled: true
    clientExistingSecret: "openwebui-sso"
    clientIdExistingSecretKey: "client_id"
    clientExistingSecretKey: "client_secret"
    providerUrl: "https://sso.d-reis.com/application/o/openwebui/.well-known/openid-configuration"
    providerName: "Authentik"
    scopes: "openid email profile"
  # roleManagement:
  #   rolesClaim: "roles"
  #   allowedRoles: ""
  #   adminRoles: ""
  groupManagement:
    groupsClaim: "groups"

logging:
  level: "info"
