global:
  domain: argo.d-reis.com

redis-ha:
  enabled: false

controller:
  replicas: 1

server:
  autoscaling:
    enabled: true
    minReplicas: 1

  insecure: true

  ingress:
    enabled: true
    ingressClassName: "traefik"

    annotations:
      external-dns.alpha.kubernetes.io/hostname: argo.d-reis.com,argo.k8s.d-reis.com
      external-dns.alpha.kubernetes.io/target: thule.d-reis.com
      cert-manager.io/cluster-issuer: letsencrypt

    tls: true

repoServer:
  autoscaling:
    enabled: true
    minReplicas: 1

applicationSet:
  replicas: 1
