apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
    app.kubernetes.io/name: openproject-dashboard
    app.kubernetes.io/part-of: openproject

configMapGenerator:
  - name: openproject-dashboard
    files:
      - openproject.json
