apiVersion: v1
kind: Service
metadata:
  name: apprise
  labels:
    app.kubernetes.io/name: apprise
    app.kubernetes.io/part-of: observability
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: apprise
  ports:
    - name: http
      port: 8000
      targetPort: http
