vikunja:
  image:
    repository: vikunja/vikunja
    tag: "2.3.0"

  ingress:
    main:
      enabled: true
      tls:
        - hosts:
            - vikunja.k8s.d-reis.com
            - todo.d-reis.com
          secretName: tls-vikunja
      hosts:
        - host: vikunja.k8s.d-reis.com
          paths:
            - path: /
        - host: todo.d-reis.com
          paths:
            - path: /

      annotations:
        external-dns.alpha.kubernetes.io/hostname: todo.d-reis.com,vikunja.k8s.d-reis.com
        external-dns.alpha.kubernetes.io/target: thule.d-reis.com
        cert-manager.io/cluster-issuer: letsencrypt

  persistence:
    data:
      enabled: true
      accessMode: ReadWriteOnce
      size: 5Gi
      mountPath: /app/vikunja/files
      storageClass: zfs
    database:
      enabled: true
      accessMode: ReadWriteOnce
      size: 2Gi
      mountPath: /db
      storageClass: zfs

  env:
    VIKUNJA_SERVICE_PUBLICURL: "https://todo.d-reis.com"
    VIKUNJA_SERVICE_ENABLEREGISTRATION: "false"

  api:
    env:
      VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_NAME: Authentik
      VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_SCOPE: "openid profile email"
      VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_LOGOUTURL:
        valueFrom:
          secretKeyRef:
            name: vikunja-sso
            key: logout_url
      VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_CLIENTID:
        valueFrom:
          secretKeyRef:
            name: vikunja-sso
            key: client_id
      VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_CLIENTSECRET:
        valueFrom:
          secretKeyRef:
            name: vikunja-sso
            key: client_secret
      VIKUNJA_AUTH_OPENID_PROVIDERS_AUTHENTIK_AUTHURL:
        valueFrom:
          secretKeyRef:
            name: vikunja-sso
            key: auth_url

  configMaps:
    config:
      enabled: true
      data:
        config.yml: |
          service:
            enableregistration: false
          auth:
            local:
              enabled: false
            openid:
              enabled: true
              providers:
                authentik:
