name: cnpg-cluster
releaseName: cnpg
namespace: cnpg-database
chartRepo: https://cloudnative-pg.github.io/charts
chart: cluster
chartVersion: 0.7.0
requirementsPath: services/base/cnpg-cluster/requirements
