apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: coredns
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://github.com/pikaro/k8s.git
      targetRevision: main
      ref: values
    - repoURL: https://coredns.github.io/helm
      chart: coredns
      targetRevision: 1.45.0
      helm:
        releaseName: coredns
        valueFiles:
          - $values/bootstrap/coredns/values.yml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
