apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true
  labels:
    grafana_dashboard: "1"
    app.kubernetes.io/name: loki-log-rates-dashboard
    app.kubernetes.io/part-of: loki
configMapGenerator:
  - name: loki-log-rates-dashboard
    files:
      - loki-log-rates.json
