apiVersion: v1
kind: Service
metadata:
  name: object-store-gateway
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "object-store-gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "object-store-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: s3
      port: {{ .Values.s3.port }}
      targetPort: s3
    - name: restic
      port: {{ .Values.restic.port }}
      targetPort: restic
