namespace: nemo-asr

labels:
  d-reis.com/context: ai
annotations:
  d-reis.com/context: ai

image:
  repository: ghcr.io/pikaro/ai-stt
  tag: sha-4e0193f

persistence:
  enabled: true
  volumes:
    - name: data
      storageClassName: zfs-temp-bulk

container:
  env:
    HF_HOME: /models/huggingface
  volumeMounts:
    - name: data
      mountPath: /models
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true
  startupProbe:
    enabled: true

service:
  port: 80

ingress:
  enabled: true
  host: stt.d-reis.com
  tls:
    secretName: nemo-asr-tls
  annotations:
    external-dns.alpha.kubernetes.io/hostname: stt.d-reis.com
    external-dns.alpha.kubernetes.io/target: thule.d-reis.com
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: traefik-forward-auth@kubernetescrd
  authentikOutpost:
    enabled: true

networkPolicy:
  ingressNamespaces:
    - openwebui
    - traefik
    - assistant
