apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: object-store-gateway-s3-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  length: 48
  digits: 12
  symbols: 0
  noUpper: false
  allowRepeat: true
  secretKeys:
    - AWS_SECRET_ACCESS_KEY
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: SSHKey
metadata:
  name: object-store-gateway-rsyncnet-ssh
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  keyType: "ed25519"
  comment: "object-store-gateway@thule"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: object-store-gateway-s3-auth
  annotations:
    argocd.argoproj.io/sync-wave: "-19"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshPolicy: CreatedOnce
  target:
    name: object-store-gateway-s3-auth
    creationPolicy: Orphan
    template:
      engineVersion: v2
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: object-store
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: object-store-gateway-s3-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: object-store-gateway-rsyncnet-ssh
  annotations:
    argocd.argoproj.io/sync-wave: "-19"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshPolicy: CreatedOnce
  target:
    name: object-store-gateway-rsyncnet-ssh
    creationPolicy: Orphan
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: SSHKey
          name: object-store-gateway-rsyncnet-ssh
