apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: object-store-gateway-s3-secret
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  length: 48
  digits: 12
  symbols: 0
  noUpper: false
  allowRepeat: true
  secretKeys:
    - AWS_SECRET_ACCESS_KEY
---
apiVersion: generators.external-secrets.io/v1alpha1
kind: SSHKey
metadata:
  name: object-store-gateway-rsyncnet-ssh
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  keyType: "ed25519"
  comment: "object-store-gateway@thule"
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: object-store-gateway-s3-auth
  annotations:
    argocd.argoproj.io/sync-wave: "-19"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshPolicy: CreatedOnce
  target:
    name: object-store-gateway-s3-auth
    creationPolicy: Orphan
    template:
      engineVersion: v2
      type: Opaque
      data:
        AWS_ACCESS_KEY_ID: object-store
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: Password
          name: object-store-gateway-s3-secret
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: object-store-gateway-rsyncnet-ssh
  annotations:
    argocd.argoproj.io/sync-wave: "-19"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshPolicy: CreatedOnce
  target:
    name: object-store-gateway-rsyncnet-ssh
    creationPolicy: Orphan
  dataFrom:
    - sourceRef:
        generatorRef:
          apiVersion: generators.external-secrets.io/v1alpha1
          kind: SSHKey
          name: object-store-gateway-rsyncnet-ssh
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: object-store-gateway-s3-auth-reader
  annotations:
    argocd.argoproj.io/sync-wave: "-18"
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["authorization.k8s.io"]
    resources: ["selfsubjectrulesreviews"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: filestash-s3-auth-reader
  annotations:
    argocd.argoproj.io/sync-wave: "-18"
subjects:
  - kind: ServiceAccount
    name: filestash-secret-reader
    namespace: files
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: object-store-gateway-s3-auth-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cnpg-backup-s3-auth-reader
  annotations:
    argocd.argoproj.io/sync-wave: "-18"
subjects:
  - kind: ServiceAccount
    name: cnpg-backup-secret-reader
    namespace: cnpg-database
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: object-store-gateway-s3-auth-reader
