apiVersion: v1
kind: Service
metadata:
  name: object-store-gateway
  labels:
    app.kubernetes.io/name: object-store-gateway
    app.kubernetes.io/part-of: object-storage
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: object-store-gateway
  ports:
    - name: s3
      port: 9000
      targetPort: s3
