type: postgresql

version:
  postgresql: "16"

mode: standalone

cluster:
  instances: 3
  imageName: ""
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []

  storage:
    size: 8Gi
    storageClass: zfs

  walStorage:
    enabled: false
    size: 1Gi
    storageClass: zfs

  # TODO: Reserve resources
  resources: {}
  priorityClassName: ""

  primaryUpdateMethod: switchover
  primaryUpdateStrategy: unsupervised
  logLevel: "info"

  # TODO: Set distribution
  affinity:
    topologyKey: topology.kubernetes.io/zone

  env: []
  envFrom: []
  certificates: {}

  enableSuperuserAccess: true
  superuserSecret: ""

  enablePDB: true

  roles:
    - name: authentik
      ensure: present
      login: true
      superuser: false
      createdb: false
      createrole: false
      replication: false
      passwordSecret:
        name: authentik-db-auth

  monitoring:
    # TODO: Enable monitoring
    enabled: false
    podMonitor:
      enabled: true
      labels: {}
      relabelings: []
      metricRelabelings: []
    prometheusRule:
      enabled: true
      excludeRules: []
    instrumentation:
      logicalReplication: true
      pgStatStatements: false
    disableDefaultQueries: false
    customQueries: []
    tls:
      enabled: false
    customQueriesSecret: []

  postgresql:
    parameters: {}
      # max_connections: 300

    synchronous: {}
    pg_hba: []
    pg_ident: []
    shared_preload_libraries: []
    ldap: {}

  replicationSlots: {}
  initdb: {}
  serviceAccountTemplate: {}
  podSecurityContext: {}
  securityContext: {}
  additionalLabels: {}
  annotations: {}

  console:
    enabled: false

backups:
  # -- You need to configure backups manually, so backups are disabled by default.
  enabled: false

  # -- Overrides the provider specific default endpoint.
  endpointURL: ""
  # Defaults to:
  # S3: https://s3.<region>.amazonaws.com"
  # Leave empty if using the default S3 endpoint

  # -- Specifies a CA bundle to validate a privately signed certificate.
  endpointCA:
    # -- Creates a secret with the given value if true, otherwise uses an existing secret.
    create: false
    name: ""
    key: ""
    value: ""

  # -- Overrides the provider specific default path.
  destinationPath: ""
  # Defaults to:
  # S3: s3://<bucket><path>
  # Azure: https://<storageAccount>.<serviceName>.core.windows.net/<containerName><path>
  # Google: gs://<bucket><path>

  # -- One of `s3`, `azure` or `google`
  provider: s3
  s3:
    region: ""
    bucket: ""
    path: "/"
    accessKey: ""
    secretKey: ""
    # -- Use the role based authentication without providing explicitly the keys
    inheritFromIAMRole: false
  azure:
    path: "/"
    connectionString: ""
    storageAccount: ""
    storageKey: ""
    storageSasToken: ""
    containerName: ""
    serviceName: blob
    inheritFromAzureAD: false
  google:
    path: "/"
    bucket: ""
    gkeEnvironment: false
    applicationCredentials: ""
  secret:
    # -- Whether to create a secret for the backup credentials
    create: true
    # -- Name of the backup credentials secret
    name: ""

  wal:
    # -- WAL compression method. One of `` (for no compression), `gzip`, `bzip2` or `snappy`.
    compression: gzip
    # -- Whether to instruct the storage provider to encrypt WAL files. One of `` (use the storage container default), `AES256` or `aws:kms`.
    encryption: AES256
    # -- Number of WAL files to be archived or restored in parallel.
    maxParallel: 1
  data:
    # -- Data compression method. One of `` (for no compression), `gzip`, `bzip2` or `snappy`.
    compression: gzip
    # -- Whether to instruct the storage provider to encrypt data files. One of `` (use the storage container default), `AES256` or `aws:kms`.
    encryption: AES256
    # -- Number of data files to be archived or restored in parallel.
    jobs: 2

  scheduledBackups:
    -
      # -- Scheduled backup name
      name: daily-backup
      # -- Schedule in cron format
      schedule: "0 0 0 * * *"
      # -- Backup owner reference
      backupOwnerReference: self
      # -- Backup method, can be `barmanObjectStore` (default) or `volumeSnapshot`
      method: barmanObjectStore

  # -- Retention policy for backups
  retentionPolicy: "30d"

databases: []
