apiVersion: v1
kind: ServiceAccount
metadata:
  name: openwebui-secret-reader
  namespace: openwebui
  annotations:
    argocd.argoproj.io/sync-wave: "-20"
---
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: cnpg-database
  namespace: openwebui
  annotations:
    argocd.argoproj.io/sync-wave: "-18"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    kubernetes:
      remoteNamespace: cnpg-database
      server:
        url: https://kubernetes.default.svc
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: openwebui-secret-reader
          namespace: openwebui
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-database
  namespace: openwebui
  annotations:
    argocd.argoproj.io/sync-wave: "-17"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    kind: SecretStore
    name: cnpg-database
  target:
    name: openwebui-database
    creationPolicy: Orphan
    template:
      engineVersion: v2
      type: Opaque
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: openwebui-db-auth
        property: username
    - secretKey: password
      remoteRef:
        key: openwebui-db-auth
        property: password
