apiVersion: generators.external-secrets.io/v1alpha1
kind: Password
metadata:
  name: openwebui-secret
  namespace: openwebui
  annotations:
    argocd.argoproj.io/sync-wave: "-15"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  length: 32
  symbols: 0
  noUpper: false
  allowRepeat: true
  secretKeys:
    - key
---
apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: openwebui-secret-export
  namespace: openwebui
  annotations:
    argocd.argoproj.io/sync-wave: "-14"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  updatePolicy: IfNotExists
  deletionPolicy: None
  secretStoreRefs:
    - name: aws-ssm
      kind: ClusterSecretStore
  selector:
    generatorRef:
      apiVersion: generators.external-secrets.io/v1alpha1
      kind: Password
      name: openwebui-secret
  data:
    - match:
        secretKey: key
        remoteRef:
          remoteKey: /external-secrets/exports/openwebui/secret-key
      metadata:
        apiVersion: kubernetes.external-secrets.io/v1alpha1
        kind: PushSecretMetadata
        spec:
          description: OpenWebUI data encryption key.
          secretType: SecureString
          kmsKeyID: alias/external-secrets
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openwebui-secret
  namespace: openwebui
  annotations:
    argocd.argoproj.io/sync-wave: "-13"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  refreshPolicy: CreatedOnce
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-ssm
  target:
    name: openwebui-secret
    creationPolicy: Orphan
    template:
      engineVersion: v2
      type: Opaque
      data:
        token: "{{ .key }}"
  data:
    - secretKey: key
      remoteRef:
        key: /external-secrets/exports/openwebui/secret-key
