namespace: stt

labels:
  d-reis.com/context: ai
annotations:
  d-reis.com/context: ai

image:
  repository: ghcr.io/pikaro/ai-stt
  tag: sha-ce7c2c1

persistence:
  enabled: true
  volumes:
    - name: data
      storageClassName: zfs-temp-bulk

container:
  env:
    HF_HOME: /models/huggingface
  volumeMounts:
    - name: data
      mountPath: /models/huggingface
  livenessProbe:
    enabled: true
  readinessProbe:
    enabled: true
  startupProbe:
    enabled: true
