{{- if .Values.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "simple-web-service.namespace" . }}
  {{- with .Values.labels }}
  labels:
{{ toYaml . | nindent 4 }}
  {{- end }}
  {{- if or .Values.privilegedMovers .Values.annotations }}
  annotations:
    {{- if .Values.privilegedMovers }}
    volsync.backube/privileged-movers: "true"
    {{- end }}
    {{- with .Values.annotations }}
{{ toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
---
{{- end }}
