sourceType: kustomize
name: filestash
namespace: files
skipDryRunOnMissingResource: "true"
extraHelmSources:
  - path: helm/volsync-restic-consumer
    releaseName: filestash-backups
    valuesFile: services/app/filestash/backups.yaml
authentik:
  name: Filestash
  protocol: proxy
  group: Files
  url: https://files.d-reis.com
  directoryGroups:
    - global-admins
    - global-users
    - filestash-admins
    - filestash-users
  proxy:
    mode: forward_single
    externalHost: https://files.d-reis.com
