name: llama-server
namespace: llama-server
sourceType: helmLocal
basePath: helm/simple-web-service
valuesFile: services/app/llama-server/values.yaml
authentik:
  name: llama-server
  slug: llama-server
  protocol: proxy
  hidden: true
  url: https://llm.d-reis.com
  directoryGroups:
    - llm-users
  accessGroups:
    - ai-users
  serviceAccounts:
    esp32: {}
  proxy:
    mode: forward_single
    externalHost: https://llm.d-reis.com
    agentTokenAuth: true
