name: openproject
chartRepo: https://charts.openproject.org
chartVersion: 13.8.1
skipDryRunOnMissingResource: "true"
createNamespace: "false"
extraHelmSources:
  - path: helm/volsync-restic-consumer
    releaseName: openproject-backups
    valuesFile: services/app/openproject/backups.yaml
requirementsPath: services/app/openproject/requirements
resourcesPath: services/app/openproject/resources
authentik:
  name: OpenProject
  group: Apps
  url: https://proj.d-reis.com
  directoryGroups:
    - global-admins
    - global-users
    - openproject-admins
    - openproject-users
  groupProperties:
    is_openproject_admin:
      groups:
        - global-admins
        - openproject-admins
  oidc:
    groupPropertyMappings:
      - is_openproject_admin
    redirectUris:
      - https://proj.d-reis.com/auth/authentik/callback
      - openprojectapp://oauth-callback
