name: openwebui
chartRepo: https://helm.openwebui.com/
chartVersion: 15.2.0
chart: open-webui
extraHelmSources:
  - path: helm/volsync-restic-consumer
    releaseName: openwebui-backups
    valuesFile: services/app/openwebui/backups.yaml
requirementsPath: services/app/openwebui/requirements
# resourcesPath: services/app/openwebui/resources
authentik:
  name: OpenWebUI
  slug: openwebui
  hidden: true
  url: https://ai.d-reis.com
  directoryGroups:
    - ai-users
    - openwebui-users
  oidc:
    redirectUris:
      - https://ai.d-reis.com/oauth/oidc/callback
