name: pockettts
namespace: pockettts
sourceType: helmLocal
basePath: helm/simple-web-service
valuesFile: services/app/pockettts/values.yaml
authentik:
  name: pockettts
  slug: pockettts
  protocol: proxy
  hidden: true
  url: https://tts.d-reis.com
  directoryGroups:
    - tts-users
  accessGroups:
    - ai-users
  serviceAccounts:
    esp32: {}
  proxy:
    mode: forward_single
    externalHost: https://tts.d-reis.com
    agentTokenAuth: true
