sourceType: kustomize
name: sso-debug
authentik:
  name: SSO Debug
  protocol: proxy
  group: Debug
  url: https://sso-debug.k8s.d-reis.com
  proxy:
    mode: forward_single
    externalHost: https://sso-debug.k8s.d-reis.com
