name: vikunja
chartRepo: oci://ghcr.io/go-vikunja/helm-chart/vikunja
chartVersion: 2.0.0
skipDryRunOnMissingResource: "true"
extraHelmSources:
  - path: helm/volsync-restic-consumer
    releaseName: vikunja-backups
    valuesFile: services/app/vikunja/backups.yaml
authentik:
  name: Vikunja
  group: Apps
  url: https://todo.d-reis.com
  directoryGroups:
    - global-admins
    - global-users
    - vikunja-admins
    - vikunja-users
  oidc:
    redirectUris:
      - https://todo.d-reis.com/auth/openid/authentik
      - vikunja-flutter://callback
